# Generated by Django 4.1.5 on 2023-01-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrifty_app', '0002_alter_post_date_created_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_posts', to='thrifty_app.user'),
        ),
    ]
