# Generated by Django 4.1.5 on 2023-02-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrifty_app', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
